@tool
class_name GeneratedBlurDisplay
extends SubViewportContainer

var preset_name: String:
	set(value):
		_preset_name_label.text = value
	
	get():
		return _preset_name_label.text

var texture_rid: RID

var texture: Texture2DRD = Texture2DRD.new()

var _preset_name_label: Label

var _full_screen_quad: FullScreenQuad


func _ready() -> void:
	_preset_name_label = Label.new()
	
	_preset_name_label.add_theme_font_size_override("font_size", 30)
	
	add_child(_preset_name_label)


func _notification(what: int) -> void:
	if what == NOTIFICATION_PREDELETE:
		var rd: RenderingDevice = RenderingServer.get_rendering_device()
		
		if !rd:
			return
		
		if texture_rid.is_valid():
			rd.free_rid(texture_rid)


func clear_environment() -> void:
	for child in get_children():
		if child == _preset_name_label:
			continue
		
		remove_child(child)
		child.queue_free()
	
	_full_screen_quad = null


func copy_environment_from_replay(replayer: Replayer) -> void:
	clear_environment()
	
	assert(replayer.is_replay_loaded(), "replayer must be set and loaded to copy the environment from")
	
	# NOTICE @sphynx-owner: I am not using duplicate() on the viewport. It seems to be completely broken,
	# forcing a snapshot of the entire world onto the new viewport without any way of updating away. Meshes
	# at the time of duplication are dangling in view, and the compositor effects from the original viewport
	# still have effect. Creating a new viewport is necessary.
	# TODO @sphynx-owner: properly implement a viewport copying method that would capture all relevant properties.
	var ref_viewport: SubViewport = ReplayUtils.safe_get_viewport(replayer)
	
	var new_viewport: SubViewport = SubViewport.new()
	
	new_viewport.own_world_3d = true
	
	new_viewport.size = ref_viewport.size
	
	add_child(new_viewport)
	
	#new_viewport.owner = owner
	
	# HACK @sphynx-owner: a way to update the SubViewportContainer's size after
	# adding the viewport as a child. Othewise it stays very small and easily gets culled away.
	new_viewport.size = new_viewport.size
	
	var new_camera: Camera3D = ref_viewport.get_camera_3d().duplicate()
	
	new_viewport.add_child(new_camera)
	
	#new_camera.owner = owner
	
	ReplayUtils.set_active_environment(new_camera, ReplayUtils.get_active_environment(replayer))
	
	ReplayUtils.set_active_camera_attributes(new_camera, ReplayUtils.get_active_camera_attributes(replayer))
	
	# NOTE @sphynx-owner: since the purpose of the display is to show a texture after it was already
	# generated by an equivalent environment, but right after the compositor stage, we can discard
	# it from the recreated environment. Basically, the reference environment provides the compositor
	# effect changes, and the recreated environments provides the tonemapping and other things we don't
	# have access to.
	# HACK @sphynx-owner: technically there could still be compounting effects from the camera attributes
	# and the environment that have effects before the compositor, so I need to be tentative about this.
	ReplayUtils.set_active_compositor(new_camera, null)
	
	_full_screen_quad = FullScreenQuad.new()
	
	new_viewport.add_child(_full_screen_quad)
	
	_full_screen_quad.texture = texture
	
	#_full_screen_quad.owner = owner
