@tool
class_name GeneratedBlurDisplay
extends SubViewportContainer

@export var replayer: Replayer

@export_tool_button("copy environment") var ed_copy_environment = copy_environment

var texture: Texture2D:
	set(value):
		if !_full_screen_quad:
			push_error("trying to set texture of blur display but missing full screen quad")
			return
		
		_full_screen_quad.texture = value
	
	get():
		if !_full_screen_quad:
			push_error("trying to get texture of blur display but missing full screen quad")
			return null
		
		return _full_screen_quad.texture

var _viewport: SubViewport

var _camera: Camera3D

var _full_screen_quad: FullScreenQuad


func _get_configuration_warnings() -> PackedStringArray:
	var ret: PackedStringArray
	
	if !replayer:
		ret.append("needs replayer to be set")
	
	return ret


func clear_environment() -> void:
	for child in get_children():
		remove_child(child)
		child.queue_free()
	
	_viewport = null
	
	_camera = null
	
	_full_screen_quad = null


func copy_environment() -> void:
	clear_environment()
	
	assert(replayer and replayer.is_replay_loaded(), "replayer must be set and loaded to copy the environment from")
	
	# NOTICE @sphynx-owner: I am not using duplicate() on the viewport. It seems to be completely broken,
	# forcing a snapshot of the entire world onto the new viewport without any way of updating away. Meshes
	# at the time of duplication are dangling in view, and the compositor effects from the original viewport
	# still have effect. Creating a new viewport is necessary.
	# TODO @sphynx-owner: properly implement a viewport copying method that would capture all relevant properties.
	var ref_viewport: SubViewport = replayer.get_viewport()
	
	var new_viewport: SubViewport = SubViewport.new()
	
	new_viewport.own_world_3d = true
	
	new_viewport.size = ref_viewport.size
	
	add_child(new_viewport)
	
	new_viewport.owner = owner
	
	# HACK @sphynx-owner: a way to update the SubViewportContainer's size after
	# adding the viewport as a child. Othewise it stays very small and easily gets culled away.
	new_viewport.size = new_viewport.size
	
	var ref_camera: Camera3D = ref_viewport.get_camera_3d()
	
	var new_camera: Camera3D = ref_camera.duplicate(DUPLICATE_DEFAULT & ~DUPLICATE_SIGNALS)
	
	var ref_environment: WorldEnvironment = ReplayUtils.find_environment_recursive(ref_viewport)
	
	# NOTE @sphynx-owner: these properties are equivalent on the _camera and the environment,
	# but the ones on the _camera take precedence. Since we are only recreating the environment
	# using _camera nodes on the displays, we just want to emulate the same conditions using
	# said cameras.
	# ----------------------------------
	if !new_camera.environment:
		new_camera.environment = ref_environment.environment
	
	if !new_camera.attributes:
		new_camera.attributes = ref_environment.camera_attributes
	
	# NOTE @sphynx-owner: since the purpose of the display is to show a texture after it was already
	# generated by an equivalent environment, but right after the compositor stage, we can discard
	# it from the recreated environment. Basically, the reference environment provides the compositor
	# effect changes, and the recreated environments provides the tonemapping and other things we don't
	# have access to.
	# HACK @sphynx-owner: technically there could still be compounting effects from the camera attributes
	# and the environment that have effects before the compositor, so I need to be tentative about this.
	#if !new_camera.compositor:
		#new_camera.compositor = ref_environment.compositor
	new_camera.compositor = null
	# ----------------------------------
	
	new_viewport.add_child(new_camera)
	
	new_camera.owner = owner
	
	_full_screen_quad = FullScreenQuad.new()
	
	new_viewport.add_child(_full_screen_quad)
	
	_full_screen_quad.owner = owner
